.TH "src Directory Reference" 3 "Tue Jul 16 2019" "Version 0.1" "tiny-todo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgui\&.c\fP"
.br
.ti -1c
.RI "file \fBpostgres\&.c\fP"
.br
.ti -1c
.RI "file \fBpostgres\&.h\fP"
.br
.ti -1c
.RI "file \fBselect_day\&.c\fP"
.br
.ti -1c
.RI "file \fBselect_day\&.h\fP"
.br
.ti -1c
.RI "file \fBspecial_allocs\&.c\fP"
.br
.ti -1c
.RI "file \fBspecial_allocs\&.h\fP"
.br
.in -1c
