.TH "src/gui.c" 3 "Thu Oct 10 2019" "Version 0.1" "tiny-todo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gui.c
.SH SYNOPSIS
.br
.PP
\fC#include <gtk/gtk\&.h>\fP
.br
\fC#include 'select_day\&.h'\fP
.br
\fC#include 'postgres\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "GtkWidget * \fBfind_child\fP (GtkWidget *parent, const char *name)"
.br
.ti -1c
.RI "void \fBadd_todo\fP (GtkWidget *addEntry, GtkWindow *window)"
.br
.ti -1c
.RI "void \fBadd_page_todays_date\fP (GtkNotebook *mainNb)"
.br
.ti -1c
.RI "GtkNotebook * \fBcreate_notebook\fP (GtkBuilder *builder)"
.br
.ti -1c
.RI "GtkWindow * \fBcreate_app\fP (GtkWindow *window)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void add_page_todays_date (GtkNotebook * mainNb)"
Creates a tab in mainNb with the tasks for the current day\&. If there is no entry in the database for the current date a new entry is created\&. This function is called on program startup\&. 
.PP
Definition at line 70 of file gui\&.c\&.
.SS "void add_todo (GtkWidget * addEntry, GtkWindow * window)"
This function gets the needed object to add a todo entry and then calls the other functions which handel the user input\&. This function is not being called anywhere in this code but there is a callback signal for the '+' button defined in glade/tiny-todo\&.glade\&. It also gets called if one presses enter in the GtkEntry\&. 
.PP
Definition at line 40 of file gui\&.c\&.
.SS "GtkWindow* create_app (GtkWindow * window)"
Initializes the main componenets like builder or the root widget, in this case the GtkWindow main_window\&. Calls \fBcreate_notebook()\fP\&. This function is just here to make \fBmain()\fP smaller and more readable\&. 
.PP
Definition at line 119 of file gui\&.c\&.
.SS "GtkNotebook* create_notebook (GtkBuilder * builder)"
Creates a GtkNotebook, adds it to a GtkBox and then calls \fBadd_page_todays_date()\fP to fill it with some content\&. 
.PP
Definition at line 100 of file gui\&.c\&.
.SS "GtkWidget* find_child (GtkWidget * parent, const char * name)"
Finds the child of the widget parent that has the name defined as the second parameter recursively\&. This function can be used to search the whole programm\&. 
.PP
Definition at line 10 of file gui\&.c\&.
.SS "int main (int argc, char ** argv)"
Just the entry point of the programm, nothing special happening here\&. 
.PP
Definition at line 138 of file gui\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny-todo from the source code\&.
