.TH "src/popups.c" 3 "Thu Oct 10 2019" "Version 0.1" "tiny-todo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/popups.c
.SH SYNOPSIS
.br
.PP
\fC#include 'popups\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBask_for_todo\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ask_for_todo (void)"

.PP
Definition at line 4 of file popups\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny-todo from the source code\&.
