.TH "src/select_day.c" 3 "Wed Jul 24 2019" "Version 0.1" "tiny-todo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/select_day.c
.SH SYNOPSIS
.br
.PP
\fC#include 'select_day\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBdate_as_str\fP ()"
.br
.ti -1c
.RI "char * \fBpretty_date_as_str\fP (char *date)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* date_as_str ()"
Makes a string out of the current_date struct\&. This is needed because this string is actually the name of the psql table corresponding to the said date\&. 
.PP
Definition at line 17 of file select_day\&.c\&.
.SS "char* pretty_date_as_str (char * date)"
makes the date string pretty for the user by replacing '_' characters with ' '\&. 
.PP
Definition at line 33 of file select_day\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny-todo from the source code\&.
